// Generates plugin/skills/foreman/reference.md from the same Zod definitions the validator uses
// (plan §8.3: schema help must come from the validator's definitions).
// Usage: bun scripts/gen-skill-reference.ts [--check]   (--check exits 1 when the file is stale)
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { z } from "zod";
import { BatchAction, LIMITS, qualifiedTool, TOOLS } from "../src/shared/protocol";
import { HANDLED_TOOLS } from "../src/shared/tools";

type JS = Record<string, any>;
const OUT = join(import.meta.dir, "..", "plugin", "skills", "foreman", "reference.md");

function typeOf(s: JS): string {
  if (s.anyOf) {
    const parts = s.anyOf.filter((x: JS) => x.type !== "null").map(typeOf);
    return parts.join(" | ") + (s.anyOf.some((x: JS) => x.type === "null") ? " | null" : "");
  }
  if (s.const !== undefined) return JSON.stringify(s.const);
  if (s.enum) return s.enum.map((e: string) => `\`${e}\``).join(" | ");
  switch (s.type) {
    case "string":
      if (s.format === "uuid") return "uuid";
      if (s.pattern === "^[A-Za-z0-9_-]{1,64}$") return "id";
      return `string ≤${s.maxLength}`;
    case "integer": {
      const max = s.maximum >= Number.MAX_SAFE_INTEGER ? "" : String(s.maximum);
      return `int ${s.minimum ?? ""}..${max}`.replace(/ \.\.$/, "");
    }
    case "boolean":
      return "boolean";
    case "array": {
      const n = s.minItems === s.maxItems && s.maxItems !== undefined ? `exactly ${s.maxItems}` : `≤${s.maxItems}`;
      return `[${typeOf(s.items)}] ${n}`;
    }
    case "object":
      return "object";
    default:
      return "?";
  }
}

function fields(s: JS, indent = ""): string[] {
  const req = new Set<string>(s.required ?? []);
  const lines: string[] = [];
  for (const [k, v] of Object.entries<JS>(s.properties ?? {})) {
    if (k === "target") continue; // stamped by the PreToolUse hook; the model never sends it
    // request_id is explained once in the header.
    const desc = v.description && k !== "request_id" ? ` — ${v.description}` : "";
    if (v.oneOf) {
      lines.push(`${indent}- \`${k}\`: one of${desc}`);
      for (const variant of v.oneOf) {
        const { kind, ...rest } = variant.properties;
        const inner = fields({ ...variant, properties: rest }, "").map((l) => l.replace(/^- /, ""));
        lines.push(`${indent}  - \`${kind.const}\`${inner.length ? ": " + inner.join("; ") : " (no extra fields)"}`);
      }
      continue;
    }
    const item = v.type === "array" && v.items?.type === "object" ? v.items : v.type === "object" ? v : null;
    lines.push(`${indent}- \`${k}\`${req.has(k) ? "" : "?"}: ${item ? (v.type === "array" ? `[object] ≤${v.maxItems}` : "object") : typeOf(v)}${desc}`);
    if (item) lines.push(...fields(item, indent + "  "));
  }
  return lines;
}

export function render(): string {
  const out = [
    "<!-- Generated by scripts/gen-skill-reference.ts from src/shared/protocol.ts. Do not edit by hand. -->",
    "# Foreman tool reference",
    "",
    "Foreman identifies your session on every call itself; never pass a `target`. Mutations take `request_id`: a fresh random UUID per call, reused only to retry the identical call.",
    "`field?` = optional. Strings are trimmed and must be nonempty; `id` = 1–64 of `A–Z a–z 0–9 _ -`. Unknown fields are rejected.",
    "Results: `{ok:true, event_id, seq, result}` after a write is persisted; `{ok:true, result}` for reads; errors `{ok:false, code, field?, message}` with code `VALIDATION`, `NOT_REGISTERED`, `STALE_TARGET`, `CONFLICT`, `LIMIT` or `STORAGE_UNAVAILABLE`.",
    `Limits: ${LIMITS.openQuestions} open questions, ${LIMITS.unreviewedDecisions} decisions awaiting review, ${LIMITS.openActionable} unresolved actionable items. Updates never consume a new slot. Word limits: \`detail\` ≤400 words, handover \`summary_md\` ≤250 words.`,
    "",
  ];
  for (const t of TOOLS.filter((x) => HANDLED_TOOLS.has(x.name))) {
    const js = z.toJSONSchema(t.input, { io: "input" }) as JS;
    out.push(`## ${t.name}`, "", `Full name: \`${qualifiedTool(t.name)}\``, "", t.description, "", ...fields(js), "");
  }
  const actions = z.toJSONSchema(BatchAction, { io: "input" }) as JS;
  out.push(
    "## Human batch actions (what arrives in a [foreman batch <id>] message)",
    "",
    "Each rendered line ends with `[action <uuid>]`; ack those ids with `foreman_inbox`.",
    "",
    ...actions.oneOf.map((v: JS) => `- \`${v.properties.type.const}\`: ${Object.keys(v.properties).filter((k) => k !== "type").join(", ")}`),
    "",
  );
  return out.join("\n");
}

if (import.meta.main) {
  const text = render();
  if (process.argv.includes("--check")) {
    let current = "";
    try {
      current = readFileSync(OUT, "utf8");
    } catch {}
    if (current !== text) {
      console.error(`${OUT} is stale; run: bun scripts/gen-skill-reference.ts`);
      process.exit(1);
    }
  } else {
    writeFileSync(OUT, text);
    console.log(`wrote ${OUT}`);
  }
}
